# Matrix Arithmetic

## Average,Variance & Standard Deviation Calculation

In [2]:
import numpy as np
matrix = np.array([[1,5,6],[5,8,0],[2,8,5]])

In [3]:
np.mean(matrix)

4.444444444444445

In [4]:
np.var(matrix)

7.358024691358025

In [5]:
np.std(matrix)

2.7125679146074897

## Reshaping & Flatteing Matrix

In [8]:
matrix = np.array([[1,5,6],[5,8,0],[2,8,5],[9,6,5]])

In [9]:
matrix

array([[1, 5, 6],
       [5, 8, 0],
       [2, 8, 5],
       [9, 6, 5]])

In [10]:
matrix.reshape(2,6)

array([[1, 5, 6, 5, 8, 0],
       [2, 8, 5, 9, 6, 5]])

In [12]:
matrix.flatten()

array([1, 5, 6, 5, 8, 0, 2, 8, 5, 9, 6, 5])

## Transpose of a matrix

In [13]:
matrix

array([[1, 5, 6],
       [5, 8, 0],
       [2, 8, 5],
       [9, 6, 5]])

In [14]:
matrix.T

array([[1, 5, 2, 9],
       [5, 8, 8, 6],
       [6, 0, 5, 5]])

## Calculating determinant


In [15]:
matrix = np.array([[1,5,6],[5,8,0],[2,8,5]])

np.linalg.det(matrix)

58.999999999999964

## Calculating diagonal and trace

In [16]:
matrix

array([[1, 5, 6],
       [5, 8, 0],
       [2, 8, 5]])

In [17]:
matrix.diagonal()

array([1, 8, 5])

In [18]:
np.fliplr(matrix)

array([[6, 5, 1],
       [0, 8, 5],
       [5, 8, 2]])

In [19]:
np.fliplr(matrix).diagonal()

array([6, 8, 2])

In [20]:
matrix.trace()

14

In [21]:
sum(matrix.diagonal())

14

## Finding eigenValues and eigenvectors

In [22]:
matrix

array([[1, 5, 6],
       [5, 8, 0],
       [2, 8, 5]])

In [23]:
eg_value,eg_vectors = np.linalg.eig(matrix)

In [25]:
eg_value

array([13.12338082+0.j        ,  0.43830959+2.07453065j,
        0.43830959-2.07453065j])

In [26]:
eg_vectors

array([[-0.54153151+0.j        , -0.74153986+0.j        ,
        -0.74153986-0.j        ],
       [-0.52849039+0.j        ,  0.45600487+0.12510378j,
         0.45600487-0.12510378j],
       [-0.65379013+0.j        , -0.31058475-0.36064435j,
        -0.31058475+0.36064435j]])

## Matrix Arithmetic

In [27]:
matrix_a = np.array([[1,2],[7,8]])
matrix_b = np.array([[4,5],[3,7]])

In [28]:
matrix_a

array([[1, 2],
       [7, 8]])

In [29]:
matrix_b

array([[4, 5],
       [3, 7]])

In [30]:
matrix_a + matrix_b

array([[ 5,  7],
       [10, 15]])

In [31]:
matrix_a @ matrix_b

array([[10, 19],
       [52, 91]])

## Inverting a square matrix

In [32]:
matrix = np.array([[1,2],[4,6]])
np.linalg.inv(matrix)

array([[-3. ,  1. ],
       [ 2. , -0.5]])

## Generating Random Array

In [36]:
print(np.random.seed(100))

None


In [34]:
np.random.random(10)

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886,
       0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333])

In [39]:
np.random.randint(0,12,7)

array([4, 2, 5, 2, 2, 2, 1])