# Imputer Class And Usages

## Imputing Missing Values

In [1]:
import numpy as np

In [2]:
x = np.array([[0,2.10,1.45],[1,2.10,1.33],[0,1.22,1.27],[1,-0.21,-1.19]])

In [3]:
x

array([[ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  2.1 ,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 1.  , -0.21, -1.19]])

In [4]:
x_with_nan = np.array([[np.nan,np.nan,1.31],[np.nan,-0.67,-0.22]])

In [5]:
x_with_nan

array([[  nan,   nan,  1.31],
       [  nan, -0.67, -0.22]])

In [6]:
from sklearn.impute import SimpleImputer

In [8]:
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')

In [9]:
x_complete = np.vstack((x_with_nan,x))

In [10]:
x_complete

array([[  nan,   nan,  1.31],
       [  nan, -0.67, -0.22],
       [ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  2.1 ,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 1.  , -0.21, -1.19]])

In [11]:
imputer.fit_transform(x_complete)

array([[ 0.  ,  2.1 ,  1.31],
       [ 0.  , -0.67, -0.22],
       [ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  2.1 ,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 1.  , -0.21, -1.19]])