
# Basic Mathematical Manipulations in Machine Learning

## Vectors,Matrix And Arrays


## Creating a Vector

In [2]:
import numpy as np

#creating a row vector

row_vector = np.array([1,2,3])
print(row_vector)

#creating a column vector
column_vector = np.array([[1],[2],[3]])
print(column_vector)


[1 2 3]
[[1]
 [2]
 [3]]


## Creating a matrix

In [9]:
#creating a 3*2 matrix
matrix = np.array([[1,2],[3,4],[6,7]])
print(matrix)
print(type(matrix))

#creating a 3*2 matrix object
matrix_object = np.mat([[1,2],[3,4],[6,7]])
print(matrix_object)
print(type(matrix_object))

[[1 2]
 [3 4]
 [6 7]]
<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [6 7]]
<class 'numpy.matrix'>


## Sparse Matrix

In [12]:
#creating a sparse matrix

from scipy import sparse
matrix = np.array([[1,0],[0,3],[9,0]])

sparse_matrix = sparse.csr_matrix(matrix)
print(sparse_matrix)

print("------------")
column_sparse_matrix = sparse.csc_matrix(matrix)
print(column_sparse_matrix)

  (0, 0)	1
  (1, 1)	3
  (2, 0)	9
------------
  (0, 0)	1
  (2, 0)	9
  (1, 1)	3


## Describing a Matrix

In [14]:
matrix = np.array([[1,2,3,4],[9,23,24,67],[2,7,9,10]])

matrix

array([[ 1,  2,  3,  4],
       [ 9, 23, 24, 67],
       [ 2,  7,  9, 10]])

In [15]:
matrix.shape

(3, 4)

In [16]:
matrix.size

12

In [17]:
matrix.ndim

2

## Performing Operations on matrix

In [19]:
operation_function = lambda p:p+10

vectorized_matrix = np.vectorize(operation_function)

vectorized_matrix(matrix)

#easy way to add 10

matrix+10

array([[11, 12, 13, 14],
       [19, 33, 34, 77],
       [12, 17, 19, 20]])

## Finding the maximum and minimum in a matrix

In [20]:
np.max(matrix)

67

In [21]:
np.min(matrix)

1