# Missing Data, RobustScaler & Categorical Introduction

## Standardization of Data Having Outliers

In [2]:
import numpy as np
from sklearn import preprocessing

In [3]:
robust_scaler = preprocessing.RobustScaler()

In [4]:
x = np.array([[-1000.1],[-200.2],[500.5],[600.6],[9000.9]])

In [5]:
x

array([[-1000.1],
       [ -200.2],
       [  500.5],
       [  600.6],
       [ 9000.9]])

In [6]:
robust_scaler.fit_transform(x)

array([[-1.87387612],
       [-0.875     ],
       [ 0.        ],
       [ 0.125     ],
       [10.61488511]])

## Deleting observation with missing Value

In [14]:
import warnings
import pandas as pd

In [10]:
warnings.simplefilter ( action='ignore',category=FutureWarning)

In [12]:
features = np.array([[1.1,11.1],[2.2,22.2],[3.3,33.3],[4.4,44.4],[np.nan,55]])

In [15]:
dataframe = pd.DataFrame(features,columns=['feature_1','feature_2'])

In [16]:
dataframe

feature_1  feature_2
0        1.1       11.1
1        2.2       22.2
2        3.3       33.3
3        4.4       44.4
4        NaN       55.0

In [17]:
dataframe.dropna()

feature_1  feature_2
0        1.1       11.1
1        2.2       22.2
2        3.3       33.3
3        4.4       44.4

## Moving from Numerical To categorical Data

In [19]:
from sklearn.preprocessing import Binarizer

In [20]:
salary = np.array([[600],[12000],[2000],[3200],[65000]])

In [21]:
salary

array([[  600],
       [12000],
       [ 2000],
       [ 3200],
       [65000]])

In [22]:
binarizer = Binarizer(8000)

In [23]:
binarizer.fit_transform(salary)

array([[0],
       [1],
       [0],
       [0],
       [1]])

In [24]:
np.digitize(salary,bins=[2000,3200,6459])

array([[0],
       [3],
       [1],
       [2],
       [3]], dtype=int64)

In [25]:
np.digitize(salary,bins=[2000,3200,6459],right=True)

array([[0],
       [3],
       [0],
       [1],
       [3]], dtype=int64)