# Feature Scalinng

## Rescaling a feature

In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
feature = np.array([[-500.5],[-100.1],[0],[100.1],[900.9]])

In [3]:
feature

array([[-500.5],
       [-100.1],
       [   0. ],
       [ 100.1],
       [ 900.9]])

In [4]:
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0,1))

In [5]:
scaled_feature = minmax_scale.fit_transform(feature)

In [6]:
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [10]:
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0,10))

In [11]:
scaled_feature = minmax_scale.fit_transform(feature)

In [12]:
scaled_feature

array([[ 0.        ],
       [ 2.85714286],
       [ 3.57142857],
       [ 4.28571429],
       [10.        ]])

## Standardizing A Feature

In [13]:
x = np.array([[-1000.1],[-200.2],[500.5],[600.6],[9000.9]])

In [14]:
x

array([[-1000.1],
       [ -200.2],
       [  500.5],
       [  600.6],
       [ 9000.9]])

In [15]:
scaler = preprocessing.StandardScaler()

In [16]:
standardized  = scaler.fit_transform(x)

In [17]:
standardized

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

## Normalizing Observations

In [21]:
from sklearn.preprocessing import Normalizer

In [24]:
features = np.array([[0.5,0.5],[1.1,3.4],[1.5,20.2],[1.63,34.4],[10.9,3.3]])

In [25]:
features

array([[ 0.5 ,  0.5 ],
       [ 1.1 ,  3.4 ],
       [ 1.5 , 20.2 ],
       [ 1.63, 34.4 ],
       [10.9 ,  3.3 ]])

In [27]:
normalizer = Normalizer(norm="l2")

In [28]:
normalizer.transform(features)

array([[0.70710678, 0.70710678],
       [0.30782029, 0.95144452],
       [0.07405353, 0.99725427],
       [0.04733062, 0.99887928],
       [0.95709822, 0.28976368]])

In [29]:
normalizer = Normalizer(norm="l1")

In [30]:
normalizer.transform(features)

array([[0.5       , 0.5       ],
       [0.24444444, 0.75555556],
       [0.06912442, 0.93087558],
       [0.04524008, 0.95475992],
       [0.76760563, 0.23239437]])